/**
 * @file        data.js
 * @description Static data used in the app.
 */


export const CARD_BG = [
  { id: 1, background: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, background: 'linear-gradient(135deg, #fef9e7 0%, #fffdfa 100%)' },
  { id: 3, background: 'linear-gradient(135deg, #eaf7f1 0%, #f3fbff 100%)' },
  { id: 4, background: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)' },
  { id: 5, background: 'linear-gradient(135deg, #e7f6f5 0%, #f4faf4 100%)' },
  { id: 6, background: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, background: 'linear-gradient(135deg, #fff4fc 0%, #fff8fb 100%)' },
  { id: 8, background: 'linear-gradient(135deg, #e8fef3 0%, #f5f8f8 100%)' },
  { id: 9, background: 'linear-gradient(135deg, #feecff 0%, #f7f5ff 100%)' },
  { id: 10, background: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' },
];


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand when ready. Dive deeper into any concept instantly with AI-powered detailed answers and explanations.",
  },
  {
    id: "03",
    title: "Continuous Discovery & Learning",
    description:
      "With one click, generate new, relevant questions based on your role — keeping your practice up to date.",
  },
  {
    id: "04",
    title: 'Understand the "Why" Behind Answers',
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Track Strengths & Weaknesses",
    description:
      "Easily identify which areas you're confident in and which need more practice — helping you focus your efforts where they count.",
  },
];


export const ROLES = [
  {
    title: "Software Engineer",
    description:
      "Software Engineers build scalable applications and solve complex technical challenges. They collaborate with cross-functional teams to design, develop, and maintain products.",
    tools: ["JavaScript", "React", "Node.js", "Docker"],
    fact: "Avg. U.S. Salary: $115,000",
  },
  {
    title: "Data Analyst",
    description:
      "Data Analysts transform raw data into insights using statistical tools and dashboards. They support strategic decision-making by identifying trends and patterns.",
    tools: ["SQL", "Python", "Tableau", "Excel"],
    fact: "Avg. U.S. Salary: $85,000",
  },
  {
    title: "Product Manager",
    description:
      "Product Managers define the product vision and roadmap while balancing user needs with business goals. They prioritize features and coordinate across teams.",
    tools: ["Jira", "Figma", "Notion", "Google Docs"],
    fact: "Avg. U.S. Salary: $120,000",
  },
  {
    title: "UX Designer",
    description:
      "UX Designers craft user-friendly experiences through research, wireframes, and usability testing. Their focus is on delivering intuitive and engaging designs.",
    tools: ["Figma", "Adobe XD", "UserTesting", "HTML/CSS"],
    fact: "Avg. U.S. Salary: $95,000",
  },
  {
    title: "Cybersecurity Analyst",
    description:
      "Cybersecurity Analysts monitor systems, investigate anomalies, and enforce security policies. Their work protects digital infrastructure from threats and vulnerabilities.",
    tools: ["SIEM", "Linux", "Python", "Splunk"],
    fact: "Avg. U.S. Salary: $105,000",
  },
  {
    title: "DevOps Engineer",
    description:
      "DevOps Engineers streamline deployments, manage cloud infrastructure, and monitor performance. They enable faster delivery through automation and CI/CD pipelines.",
    tools: ["Docker", "AWS", "Terraform", "Kubernetes"],
    fact: "Avg. U.S. Salary: $125,000",
  },
  {
  title: "Machine Learning Engineer",
  description:
    "Machine Learning Engineers build and deploy AI models that power intelligent applications. They work on training algorithms, optimizing performance, and integrating ML systems into production pipelines.",
  tools: ["Python", "TensorFlow", "PyTorch", "AWS SageMaker"],
  fact: "Avg. U.S. Salary: $130,000",
},
{
  title: "Cloud Solutions Architect",
  description:
    "Cloud Architects design scalable, secure, and cost-effective cloud infrastructure. They guide teams in selecting cloud services, define system architecture, and ensure high availability and performance.",
  tools: ["AWS", "Azure", "Terraform", "Kubernetes"],
  fact: "Avg. U.S. Salary: $145,000",
},
{
  title: "Full-Stack Developer",
  description:
    "Full-Stack Developers work across both frontend and backend technologies to build complete web applications. They understand UI design, databases, server logic, and API integration.",
  tools: ["React", "Node.js", "MongoDB", "Express.js"],
  fact: "Avg. U.S. Salary: $110,000",
},
{
  title: "Technical Program Manager",
  description:
    "Technical Program Managers oversee cross-functional engineering projects, aligning technical implementation with business goals. They manage timelines, stakeholders, and product delivery.",
  tools: ["Jira", "Confluence", "Slack", "Asana"],
  fact: "Avg. U.S. Salary: $135,000",
}
];